config/routes.rb
Rails.application.routes.draw do

  
  
  devise_for :models
  root "users#index"
  resources :users do
    resources :comments
  end
  
  
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :model
end

app/models/model.rb
class Model < ActiveRecord::Base
	has_many :users
	has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable ,:confirmable
end

app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :model
	has_many :comments
	mount_uploader :image,ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #config.action_mailer.default_url_option = {host: 'hidden-spire-1398.herokuapp.com'}
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
       @user = User.find(params[:user_id])
       @comment = @user.comments.create(params[:comment].permit(:comment))
       @comment.model_id = current_model.id if current_model
       if @comment.save
       	redirect_to user_path(@user)
       else
       	render 'new'
	end
end

def destroy
	@user =User.find(params[:user_id])
	@comment = @user.comments.find(params[:id])
	@comment.destroy
	redirect_to user_path(@user)


end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_model!,except:[:index, :show]
	def index
		@users = User.all.order("created_at DESC")
		
	end

	def new
		@user = current_model.users.build #User.new
		
	end

	def create
       @user = current_model.users.build(allowed_params)#User.new(allowed_params)

       if @user.save 
       	redirect_to users_path
       else
       	  rendender 'new'
       	end
		
	end

	def show
		@user =User.find(params[:id])
		
	end
	def edit
		@user =User.find(params[:id])
		
	end

	def update
		@user =User.find(params[:id])
		if @user.update_attributes(allowed_params)
       	redirect_to users_path
       else
       	  rendender 'edit'
       	end
	

		
	end
	def destroy
		@user =User.find(params[:id])
		@user.comments.destroy_all
		@user.destroy
		redirect_to users_path
		
	end

	def complete 

		#User.where(:id => params[:mark_ids]).destroy_all
		#respond_to do |format|
		#	format.html{redirect_to users_path}
		#	format.js
		#end
		
		

		#redirect_to users_path
	end 

 	def destroy_multiple

     User.destroy(params[:users])



     respond_to do |format|
     format.html { redirect_to users_path }
     format.json { head :no_content }
     end

  

     end

	private
	def allowed_params
		params.require(:user).permit(:name,:age,:image)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	
end

app/views/comments/_comment.html.erb
<% if model_signed_in? %>
     
    <% if current_model.id == comment.model_id %>
        <%= comment.comment %> by <%= comment.model.email %>
        <%= link_to "delete",[comment.user , comment] ,method: :delete , data:{confirm: "are you sure" }%> <br />
     <% else %>
     <%= comment.comment %> by <%= comment.model.email %><br />
<% end %>

<%end %>

 

app/views/comments/_form.html.erb
<%= form_for([@user,@user.comments.build]) do |f| %>
<%= f.text_field :comment %>
<%= f.submit %>
<% end %>

app/views/comments/_formm.html.erb
<%= form_for([User,user.comments.build]) do |f| %>
<%= f.text_field :comment %>
<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snehasish's Rails forum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/users/complete.html.erb
<%= link_to '<button type="button"><h1>DISPLAY</h1></button>'.html_safe ,users_path %>
<%= link_to '<button type="button"><h1>NEW USER DATABASE</h1></button>'.html_safe ,new_user_path %>

app/views/users/edit.html.erb
<%= link_to 'go back',users_path %>
<%= form_for @user , html: { multipart: true } do |f| %>
<%= image_tag @user.image.url(:thumb) %><br />
<%= f.file_field :image %> <br />
<%= f.label :title%><br /> <%= f.text_field :name %> <br />
<%= f.label :content %> <br /><%= f.text_field :age %><br />
<%= f.submit 'save '%>


<% end %>

app/views/users/index.html.erb
<% if model_signed_in? %>
<%= link_to('Logout', destroy_model_session_path, :method => :delete) %>
<h3><%= link_to ' new user database' , new_user_path %></h3><br />
<% else %>
<h3><%= link_to ' sign_up' ,new_model_registration_path  %> | <%= link_to ' sign_in' , new_model_session_path %></h3>
<% end %>
<% @users.each do |user| %>

<%= link_to  user.name ,user_path(user) %><br />  
<%= user.age %><br />  
published at <%= time_ago_in_words(user.created_at)%><br />
by <%= user.model.email %><br />

<% if (current_model == user.model) %>
<%= link_to 'Edit' , edit_user_path(user) %> |
<%= link_to 'Delete', user , method: :delete , data: {confirm: "want to do ?"} %><br />
<% end %> 



<% if model_signed_in? %>
    Comments :<%= user.comments.count %><br />
    <% if user.comments.count != 0 %>
         <%= render user.comments %><br />
     <%end%>

<% end %>


<% end %>



 

app/views/users/new.html.erb
<%= image_tag @user.image.url(:thumb) %>
<%= form_for @user , html: { multipart: true } do |f| %> 
<%= f.label :image%><br /> <%= f.file_field :image %> <br />
<%= f.label :title%><br /> <%= f.text_field :name %> <br />
<%= f.label :content %> <br /><%= f.text_field :age %><br />
<%= f.submit 'save '%>
<% end %>

app/views/users/show.html.erb
<%= link_to 'go back',users_path %>
<h5><%=image_tag @user.image_url(:thumb).to_s%></h5>
<h5><%= @user.name %></h5>
<h5><%= @user.age %></h5>
comments : <%= @user.comments.count %><br />
<%= render @user.comments %>
<% if model_signed_in? %>
<h5>Write comment<br /><%= render "comments/form" %></h5>
<%end%>